# Generated by Django 5.1.4 on 2026-05-21 14:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("max_concurrent_loans", models.PositiveIntegerField(default=3)),
                ("default_loan_duration_days", models.PositiveIntegerField(default=21)),
                (
                    "allowed_document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de codes DocumentType ; vide = tous autorisés.",
                    ),
                ),
                ("card_validity_months", models.PositiveIntegerField(default=12)),
            ],
            options={
                "verbose_name": "catégorie d'usager",
                "verbose_name_plural": "catégories d'usager",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=13, unique=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                ("registration_date", models.DateField(default=datetime.date.today)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("expired", "Expiré"),
                            ("closed", "Clôturé"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("preferred_language", models.CharField(blank=True, default="", max_length=10)),
                ("replaces_card_number", models.CharField(blank=True, max_length=13)),
                ("photo", models.FileField(blank=True, null=True, upload_to="member_photos/")),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte collectif parent (école/famille).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="members.member",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="members.membercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "usager",
                "verbose_name_plural": "usagers",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["last_name", "first_name"], name="member_name_idx")
                ],
            },
        ),
    ]
