# Generated by Django 5.1.4 on 2026-08-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_backfill_translation_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='member',
            name='spoken_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='langues parlées'),
        ),
        migrations.AddField(
            model_name='member',
            name='spoken_languages_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='autres langues'),
        ),
        migrations.CreateModel(
            name='MemberChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('gender', models.CharField(blank=True, choices=[('f', 'Fille'), ('m', 'Garçon'), ('x', 'Autre')], max_length=1, verbose_name='sexe')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='âge')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='langues parlées')),
                ('languages_other', models.CharField(blank=True, max_length=200, verbose_name='autres langues')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.member')),
            ],
            options={
                'verbose_name': 'enfant',
                'verbose_name_plural': 'enfants',
                'ordering': ['first_name'],
            },
        ),
    ]
