# Generated by Django 5.1.4 on 2026-08-21 08:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberfamilymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='n° de carte'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.membercategory', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration"),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='member_photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='langue de correspondance'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='member',
            name='replaces_card_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='ancienne carte'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('expired', 'Expiré'), ('closed', 'Clôturé')], default='active', max_length=15, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='name_es',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='membercategory',
            name='name_mg',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
    ]
