# Generated by Django 5.1.4 on 2026-09-09 16:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_contact_and_membership_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "renewed_on",
                    models.DateField(default=datetime.date.today, verbose_name="renouvelée le"),
                ),
                (
                    "previous_expiration",
                    models.DateField(blank=True, null=True, verbose_name="ancienne expiration"),
                ),
                ("new_expiration", models.DateField(verbose_name="nouvelle expiration")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_renewals",
                        to="members.member",
                        verbose_name="usager",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_renewals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enregistrée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "renouvellement de carte",
                "verbose_name_plural": "renouvellements de carte",
                "ordering": ["-renewed_on", "-id"],
                "indexes": [models.Index(fields=["renewed_on"], name="card_renewal_date_idx")],
            },
        ),
    ]
