# Generated by Django 5.1.4 on 2026-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='always_show_advanced',
            field=models.BooleanField(default=False, verbose_name='toujours afficher les options avancées'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='langue par défaut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('librarian', 'Bibliothécaire'), ('contributor_api', 'Contributeur OfeliaScan'), ('readonly', 'Support / lecture seule')], default='librarian', max_length=20, verbose_name='rôle'),
        ),
    ]
