# Generated by Django 5.1.4 on 2026-08-31 19:13

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0007_member_contact_and_membership_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("membership", "Cotisation"),
                            ("activity", "Animation"),
                            ("fine", "Amende"),
                            ("other", "Autre"),
                        ],
                        default="fine",
                        max_length=20,
                        verbose_name="nature",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="libellé")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="montant proposé",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "tarif",
                "verbose_name_plural": "tarifs",
                "ordering": ["kind", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="n° de facture"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(default=datetime.date.today, verbose_name="date d'émission"),
                ),
                ("due_date", models.DateField(verbose_name="échéance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "À régler"),
                            ("paid", "Réglée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="open",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10, verbose_name="total"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10, verbose_name="réglé"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emailed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="envoyée le"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="relancée le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="émise par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="members.member",
                        verbose_name="usager",
                    ),
                ),
            ],
            options={
                "verbose_name": "facture",
                "verbose_name_plural": "factures",
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("membership", "Cotisation"),
                            ("activity", "Animation"),
                            ("fine", "Amende"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="nature",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="libellé")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant unitaire"
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1, verbose_name="quantité")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de facture",
                "verbose_name_plural": "lignes de facture",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("invoice", "Facture"), ("reminder", "Relance")],
                        max_length=15,
                        verbose_name="nature",
                    ),
                ),
                ("to_address", models.EmailField(max_length=254, verbose_name="destinataire")),
                ("subject", models.CharField(max_length=250, verbose_name="objet")),
                ("body", models.TextField(verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="erreur")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="tentatives"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="envoyé le")),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="finance.invoice",
                        verbose_name="facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "email en file",
                "verbose_name_plural": "emails en file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="montant"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Espèces"), ("transfer", "Virement"), ("other", "Autre")],
                        default="cash",
                        max_length=15,
                        verbose_name="mode de paiement",
                    ),
                ),
                ("paid_on", models.DateField(default=datetime.date.today, verbose_name="date")),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                        verbose_name="facture",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="encaissé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-paid_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_on", models.DateField(default=datetime.date.today, verbose_name="date")),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Entrée"), ("out", "Sortie")],
                        max_length=5,
                        verbose_name="sens",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="montant"),
                ),
                ("label", models.CharField(max_length=200, verbose_name="libellé")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="saisi par",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_movement",
                        to="finance.payment",
                        verbose_name="paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de caisse",
                "verbose_name_plural": "mouvements de caisse",
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status", "due_date"], name="invoice_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(fields=["occurred_on"], name="cash_date_idx"),
        ),
    ]
