# Generated by Django 5.1.4 on 2026-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("key", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "paramètre",
                "verbose_name_plural": "paramètres",
                "ordering": ["key"],
            },
        ),
    ]
