# Generated by Django 5.1.4 on 2026-05-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_mobile_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorysession",
            name="relocate_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
