# Generated by Django 5.1.4 on 2026-08-21 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_bibliographicrecord_authors_and_more'),
        ('inventory', '0003_inventorysession_relocate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysession',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='scope_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='scope_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location', verbose_name='emplacement'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='scope_type',
            field=models.CharField(choices=[('all', 'Tout le fonds'), ('location', 'Un emplacement'), ('category', 'Une catégorie')], default='all', max_length=10, verbose_name='périmètre'),
        ),
    ]
