# Generated by Django 5.1.4 on 2026-08-31 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0007_member_contact_and_membership_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=120, unique=True, verbose_name="libellé")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "nature d'activité",
                "verbose_name_plural": "natures d'activité",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="AnimationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=150, unique=True, verbose_name="intitulé")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animation_types_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "type d'animation",
                "verbose_name_plural": "types d'animation",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="AnimationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_on", models.DateField(default=datetime.date.today, verbose_name="date")),
                ("minutes", models.PositiveIntegerField(verbose_name="temps passé (minutes)")),
                (
                    "non_member_adults",
                    models.PositiveIntegerField(default=0, verbose_name="non-membres adultes"),
                ),
                (
                    "non_member_children",
                    models.PositiveIntegerField(default=0, verbose_name="non-membres enfants"),
                ),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animations_presented",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="animateur",
                    ),
                ),
                (
                    "animation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="closing.animationtype",
                        verbose_name="animation",
                    ),
                ),
            ],
            options={
                "verbose_name": "animation",
                "verbose_name_plural": "animations",
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DayClosing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(default=datetime.date.today, verbose_name="date"),
                ),
                ("closed_at", models.DateTimeField(auto_now=True)),
                ("activities_done", models.BooleanField(default=False)),
                ("cash_reviewed", models.BooleanField(default=False)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_queued", models.PositiveIntegerField(default=0)),
                ("backup_status", models.CharField(blank=True, max_length=20)),
                ("backup_detail", models.CharField(blank=True, max_length=250)),
                ("shutdown_requested", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="note")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="day_closings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "bouclement",
                "verbose_name_plural": "bouclements",
                "ordering": ["-closing_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_on", models.DateField(default=datetime.date.today, verbose_name="date")),
                ("minutes", models.PositiveIntegerField(verbose_name="temps passé (minutes)")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employé",
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="closing.activitytype",
                        verbose_name="activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "activité",
                "verbose_name_plural": "activités",
                "ordering": ["-occurred_on", "-id"],
                "indexes": [models.Index(fields=["occurred_on"], name="activity_date_idx")],
            },
        ),
        migrations.CreateModel(
            name="AnimationAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animation_attendances",
                        to="members.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="closing.animationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "présence",
                "verbose_name_plural": "présences",
                "ordering": ["member__last_name", "member__first_name"],
                "unique_together": {("session", "member")},
            },
        ),
        migrations.AddIndex(
            model_name="animationsession",
            index=models.Index(fields=["occurred_on"], name="animation_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dayclosing",
            unique_together={("closing_date", "user")},
        ),
    ]
