# Generated by Django 5.1.4 on 2026-05-21 14:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InHouseConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="catalog.item",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "consultation sur place",
                "verbose_name_plural": "consultations sur place",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("loan_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("renewal_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "En cours"),
                            ("returned", "Retourné"),
                            ("overdue", "En retard"),
                            ("lost", "Perdu"),
                            ("written_off", "Radié"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="catalog.item",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "prêt",
                "verbose_name_plural": "prêts",
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ready_for_pickup", "Prêt à retirer"),
                            ("fulfilled", "Honorée"),
                            ("expired", "Expirée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ready_since", models.DateField(blank=True, null=True)),
                (
                    "fulfilled_by_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_reservations",
                        to="catalog.item",
                    ),
                ),
                (
                    "fulfilled_by_loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilling_reservations",
                        to="loans.loan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="members.member",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.bibliographicrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "réservation",
                "verbose_name_plural": "réservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["member", "status"], name="loan_member_status_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["due_date", "status"], name="loan_due_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_idx"),
        ),
    ]
