# Generated by Django 5.1.4 on 2026-05-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
