# Generated by Django 5.1.4 on 2026-08-21 08:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_reservation_notified_at'),
        ('members', '0006_alter_member_address_alter_member_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhouseconsultation',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='inhouseconsultation',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='inhouseconsultation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='members.member', verbose_name='usager'),
        ),
    ]
