# Generated by Django 5.1.4 on 2026-05-21 14:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=200)),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "auteur",
                "verbose_name_plural": "auteurs",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("color", models.CharField(blank=True, help_text="Hex ex: #ff8800", max_length=7)),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("default_loan_duration_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BibliographicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="fr", max_length=10)),
                ("isbn_13", models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ("isbn_10", models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ("summary", models.TextField(blank=True)),
                ("cover_image", models.FileField(blank=True, null=True, upload_to="covers/")),
                ("series_name", models.CharField(blank=True, max_length=200)),
                ("series_volume", models.CharField(blank=True, max_length=20)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("book", "Livre"),
                            ("magazine_issue", "Numéro de magazine"),
                            ("newspaper", "Journal"),
                            ("comic", "BD / manga"),
                            ("audio_cd", "CD audio"),
                            ("other", "Autre"),
                        ],
                        default="book",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metadata_source",
                    models.CharField(
                        choices=[
                            ("manual", "Saisie manuelle"),
                            ("openlibrary", "OpenLibrary"),
                            ("scan_app", "OfeliaScan"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "metadata_quality",
                    models.CharField(
                        choices=[
                            ("verified", "Vérifiée"),
                            ("auto", "Automatique"),
                            ("partial", "Partielle"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(blank=True, related_name="records", to="catalog.author"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="catalog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="records", to="catalog.tag"),
                ),
            ],
            options={
                "verbose_name": "notice bibliographique",
                "verbose_name_plural": "notices bibliographiques",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "emplacement",
                "verbose_name_plural": "emplacements",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("internal_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("ean13", models.CharField(blank=True, max_length=13, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "Neuf"),
                            ("good", "Bon"),
                            ("worn", "Usé"),
                            ("damaged", "Abîmé"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("acquisition_date", models.DateField(default=datetime.date.today)),
                (
                    "acquisition_source",
                    models.CharField(
                        choices=[
                            ("purchase", "Achat"),
                            ("donation", "Don"),
                            ("exchange", "Échange"),
                            ("unknown", "Inconnu"),
                        ],
                        default="unknown",
                        max_length=15,
                    ),
                ),
                ("donor", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("on_loan", "Prêté"),
                            ("reserved_for_pickup", "Mis de côté"),
                            ("in_repair", "En réparation"),
                            ("lost", "Perdu"),
                            ("discarded", "Pilonné"),
                        ],
                        default="available",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.bibliographicrecord",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "exemplaire",
                "verbose_name_plural": "exemplaires",
                "ordering": ["internal_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("code", "parent"), name="location_code_parent_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status", "location"], name="item_status_location_idx"),
        ),
        migrations.AddConstraint(
            model_name="bibliographicrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isbn_13__isnull", False)),
                fields=("isbn_13",),
                name="record_isbn13_unique_not_null",
            ),
        ),
    ]
