# Generated by Django 5.1.4 on 2026-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_fts5"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_es",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_fr",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_mg",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_es",
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_fr",
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_mg",
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
