# Generated by Django 5.1.4 on 2026-05-23 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_scan_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("finished", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fill_missing", "Compléter les champs vides uniquement"),
                            ("overwrite", "Écraser avec les données externes"),
                        ],
                        default="fill_missing",
                        max_length=20,
                    ),
                ),
                ("sources", models.JSONField(default=list)),
                ("scope_filter", models.JSONField(default=dict)),
                ("total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("report", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrichment_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "enrichissement métadonnées",
                "verbose_name_plural": "enrichissements métadonnées",
                "ordering": ["-started_at"],
            },
        ),
    ]
