# Generated by Django 5.1.4 on 2026-05-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_enrichmentjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiredItemCode",
            fields=[
                ("internal_id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("ean13", models.CharField(blank=True, max_length=13)),
                ("record_title_snapshot", models.CharField(blank=True, max_length=255)),
                ("retired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("bulk_delete", "Suppression en masse de notices"),
                            ("item_delete", "Suppression d'exemplaire"),
                        ],
                        default="item_delete",
                        max_length=20,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retired_item_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "code Ofelia retiré",
                "verbose_name_plural": "codes Ofelia retirés",
                "ordering": ["-retired_at"],
                "indexes": [models.Index(fields=["internal_id"], name="retired_internal_id_idx")],
            },
        ),
    ]
