# Generated by Django 5.1.4 on 2026-06-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_excel_catalog_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentjob",
            name="rate_limited",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="excelcatalogjob",
            name="rate_limited",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
