# Generated by Django 5.1.4 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_scansession_input_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_code',
            field=models.CharField(blank=True, db_index=True, help_text="Code déjà porté par le livre, jusqu'à 20 caractères. Ex. BCF13298781X.", max_length=20, verbose_name='code Ofelia externe'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('external_code', ''), _negated=True), fields=('external_code',), name='item_external_code_unique_not_blank'),
        ),
    ]
