# Generated by Django 5.1.4 on 2026-08-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_item_external_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'provenance',
                'verbose_name_plural': 'provenances',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.provenance', verbose_name='provenance'),
        ),
        migrations.AddField(
            model_name='scansession',
            name='default_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sessions', to='catalog.provenance'),
        ),
    ]
