# Generated by Django 5.1.4 on 2026-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_provenance_item_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='abréviation'),
        ),
    ]
