# Generated by Django 5.1.4 on 2026-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_fr', models.CharField(max_length=80, null=True)),
                ('name_en', models.CharField(max_length=80, null=True)),
                ('name_es', models.CharField(max_length=80, null=True)),
                ('name_mg', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'langue',
                'verbose_name_plural': 'langues',
                'ordering': ['code'],
            },
        ),
    ]
