# Generated by Django 5.1.4 on 2026-08-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_normalize_record_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='records', to='catalog.author', verbose_name='auteurs'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='catalog.category', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='covers/', verbose_name='couverture'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='document_type',
            field=models.CharField(choices=[('book', 'Livre'), ('magazine_issue', 'Numéro de magazine'), ('newspaper', 'Journal'), ('comic', 'BD / manga'), ('audio_cd', 'CD audio'), ('other', 'Autre')], default='book', max_length=20, verbose_name='type de document'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='isbn_10',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='ISBN-10'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='isbn_13',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='ISBN-13'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='language',
            field=models.CharField(blank=True, default='fr', max_length=10, verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='année de publication'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='éditeur'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='series_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='série'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='series_volume',
            field=models.CharField(blank=True, max_length=20, verbose_name='tome'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='sous-titre'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='summary',
            field=models.TextField(blank=True, verbose_name='résumé'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='records', to='catalog.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_mg',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=20, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
